// <auto-generated />
using System;
using C01.SqlQuery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace C03.CascadeDelete.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230921231752_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("C03.CascadeDelete.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("C03.CascadeDelete.Entities.AuthorV2", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("AuthorV2s", (string)null);
                });

            modelBuilder.Entity("C03.CascadeDelete.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("C03.CascadeDelete.Entities.BookV2", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorV2Id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("AuthorV2Id");

                    b.ToTable("BookV2s", (string)null);
                });

            modelBuilder.Entity("C03.CascadeDelete.Entities.Book", b =>
                {
                    b.HasOne("C03.CascadeDelete.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("C03.CascadeDelete.Entities.BookV2", b =>
                {
                    b.HasOne("C03.CascadeDelete.Entities.AuthorV2", "AuthorV2")
                        .WithMany("BookV2s")
                        .HasForeignKey("AuthorV2Id");

                    b.Navigation("AuthorV2");
                });

            modelBuilder.Entity("C03.CascadeDelete.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("C03.CascadeDelete.Entities.AuthorV2", b =>
                {
                    b.Navigation("BookV2s");
                });
#pragma warning restore 612, 618
        }
    }
}
